#!/usr/bin/env bash
set -e

cd ~

curl -sL https://deb.nodesource.com/setup_12.x -o nodesource_setup.sh
sudo bash nodesource_setup.sh
sudo apt install -y nodejs build-essential


echo "Node Version BEGIN"
node --version
echo "Node Version END"

jupyter serverextension enable jupyterlab
jupyter nbextension enable --py widgetsnbextension --sys-prefix
jupyter nbextension enable --py plotlywidget --sys-prefix

jupyter labextension install @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension install jupyterlab-plotly@4.11.0 --no-build
jupyter labextension install plotlywidget@4.11.0 --no-build
jupyter labextension enable @jupyter-widgets/jupyterlab-manager --no-build
jupyter labextension enable jupyterlab-plotly@4.11.0 --no-build
jupyter labextension enable plotlywidget@4.11.0 --no-build
#
git clone https://github.com/jheinnic/jupyter_clickable_image_widget
cd jupyter_clickable_image_widget
#
pip install -e .
#
jupyter labextension install js --no-build
jupyter labextension enable js --no-build
#
cd ..
#
jupyter lab build --minimize=False
#
rm -rf jupyter_clickable_image_widget
