channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=2.2.8
- jupyter-core=4.6.3
- jupyter-kernel-gateway=2.4.3
- nodejs=14
- nbconvert=5.5
- widgetsnbextension=3.5.1
# Python Kernel
- python=3.7
- aiochannel
- certifi=2020.6.20
- decorator<5,>=4.3
- ipywidgets=7.5.1
- numpy=1.19.1
- pandas=1.1.1
- pillow=7.2.0
- plotly=4.11.0
- protobuf=3.12.4
- scikit-image=0.17.2
- scikit-learn=0.23.2
- scipy=1.5.2
- traitlets=5.0.4
- uuid=1.30
- dask=2.1
- matplotlib=3
